# Generated by Django 6.0.3 on 2026-05-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
